-- Generated by npm run db:sql. Edit backend/migrations sources, then regenerate.
-- Schema only: does not initialize accounts/data or mark the app ready.
-- Source: backend/migrations/001_supabase.sql
-- Run as the database owner in Supabase Studio's SQL editor or with psql.
-- The Go API is the authorization boundary. This schema is NOT a public Data API.
BEGIN;
CREATE SCHEMA IF NOT EXISTS career_quest;
REVOKE ALL ON SCHEMA career_quest FROM PUBLIC;

CREATE TABLE IF NOT EXISTS career_quest.store_meta (
    id integer PRIMARY KEY CHECK (id = 1),
    schema_version integer NOT NULL,
    ready boolean NOT NULL DEFAULT false
);
INSERT INTO career_quest.store_meta (id, schema_version) VALUES (1, 1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS career_quest.imports (
    checksum text PRIMARY KEY,
    imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS career_quest.skills (
    sort_order integer NOT NULL UNIQUE,
    skill_id text PRIMARY KEY,
    name text NOT NULL,
    type text NOT NULL CHECK (type IN ('hard', 'soft')),
    category text NOT NULL,
    description text NOT NULL
);
CREATE TABLE IF NOT EXISTS career_quest.role_profiles (
    sort_order integer NOT NULL UNIQUE,
    role text NOT NULL,
    grade text NOT NULL CHECK (grade IN ('Junior', 'Middle', 'Senior', 'Lead')),
    required_skills jsonb NOT NULL CHECK (jsonb_typeof(required_skills) = 'object'),
    critical_skills jsonb,
    PRIMARY KEY (role, grade)
);
CREATE TABLE IF NOT EXISTS career_quest.employees (
    sort_order integer NOT NULL UNIQUE,
    employee_id text PRIMARY KEY,
    full_name text NOT NULL,
    department text NOT NULL,
    role text NOT NULL,
    grade text NOT NULL,
    manager_id text REFERENCES career_quest.employees(employee_id) DEFERRABLE INITIALLY DEFERRED,
    hire_date date NOT NULL,
    tenure_months integer NOT NULL CHECK (tenure_months >= 0),
    work_format text NOT NULL CHECK (work_format IN ('office', 'hybrid', 'remote')),
    preferred_language text NOT NULL CHECK (preferred_language IN ('kk', 'ru', 'en')),
    career_goal jsonb,
    skills jsonb NOT NULL CHECK (jsonb_typeof(skills) = 'object'),
    last_review_date date NOT NULL,
    FOREIGN KEY (role, grade) REFERENCES career_quest.role_profiles(role, grade) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS career_quest.events (
    sort_order integer NOT NULL UNIQUE,
    event_id text PRIMARY KEY,
    title text NOT NULL,
    description text NOT NULL,
    type text NOT NULL,
    format text NOT NULL CHECK (format IN ('online', 'offline', 'self_paced')),
    duration_hours double precision NOT NULL CHECK (duration_hours >= 0),
    mandatory boolean NOT NULL,
    target_roles jsonb,
    target_grades jsonb,
    develops_skills jsonb,
    prerequisites jsonb,
    upcoming_sessions jsonb
);
CREATE TABLE IF NOT EXISTS career_quest.activity_history (
    -- Preserve input ordering for same-day skill gains with different caps.
    sort_order integer NOT NULL UNIQUE,
    record_id text PRIMARY KEY,
    employee_id text NOT NULL REFERENCES career_quest.employees(employee_id) DEFERRABLE INITIALLY DEFERRED,
    event_id text NOT NULL REFERENCES career_quest.events(event_id) DEFERRABLE INITIALLY DEFERRED,
    date date NOT NULL,
    due_date date,
    status text NOT NULL CHECK (status IN ('completed', 'in_progress', 'dropped', 'no_show', 'declined', 'overdue')),
    completion_pct integer NOT NULL CHECK (completion_pct BETWEEN 0 AND 100),
    -- Strings preserve the original CSV/API contract, including an empty score.
    score text NOT NULL CHECK (score = '' OR score ~ '^(100|[0-9]{1,2})$'),
    feedback_rating text NOT NULL CHECK (feedback_rating = '' OR feedback_rating ~ '^[1-5]$'),
    assigned_by text NOT NULL CHECK (assigned_by IN ('self', 'manager', 'hr'))
);
CREATE TABLE IF NOT EXISTS career_quest.app_users (
    sort_order integer NOT NULL UNIQUE,
    id text PRIMARY KEY,
    login text NOT NULL UNIQUE CHECK (login = lower(login)),
    password_hash text NOT NULL,
    role text NOT NULL CHECK (role IN ('employee', 'manager', 'hr')),
    employee_id text UNIQUE REFERENCES career_quest.employees(employee_id) DEFERRABLE INITIALLY DEFERRED,
    CHECK (role = 'hr' OR employee_id IS NOT NULL)
);
CREATE TABLE IF NOT EXISTS career_quest.requests (
    sort_order integer NOT NULL UNIQUE,
    id text PRIMARY KEY,
    employee_id text NOT NULL REFERENCES career_quest.employees(employee_id) DEFERRABLE INITIALLY DEFERRED,
    event_id text NOT NULL REFERENCES career_quest.events(event_id) DEFERRABLE INITIALLY DEFERRED,
    status text NOT NULL CHECK (status IN ('pending_manager', 'approved', 'pending_hr', 'completed', 'declined', 'rejected', 'cancelled')),
    session_date date,
    -- RFC3339 text preserves the API's exact timestamp precision and signatures.
    created_at text NOT NULL,
    updated_at text NOT NULL,
    evidence text NOT NULL,
    note text NOT NULL,
    gains jsonb,
    confirmed_by text REFERENCES career_quest.app_users(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX IF NOT EXISTS requests_one_active_event ON career_quest.requests(employee_id, event_id)
    WHERE status IN ('pending_manager', 'approved', 'pending_hr');
CREATE TABLE IF NOT EXISTS career_quest.audit_log (
    sort_order integer NOT NULL UNIQUE,
    id text PRIMARY KEY,
    actor text NOT NULL REFERENCES career_quest.app_users(id) DEFERRABLE INITIALLY DEFERRED,
    role text NOT NULL,
    employee_id text REFERENCES career_quest.employees(employee_id) DEFERRABLE INITIALLY DEFERRED,
    entity_id text NOT NULL,
    action text NOT NULL,
    detail text NOT NULL,
    at text NOT NULL
);
CREATE TABLE IF NOT EXISTS career_quest.recommendations (
    sort_order integer NOT NULL UNIQUE,
    id text PRIMARY KEY,
    employee_id text NOT NULL REFERENCES career_quest.employees(employee_id) DEFERRABLE INITIALLY DEFERRED,
    model text NOT NULL,
    at text NOT NULL,
    choices jsonb,
    signature text NOT NULL,
    evidence jsonb
);
CREATE TABLE IF NOT EXISTS career_quest.sessions (
    token_hash text PRIMARY KEY CHECK (length(token_hash) = 64),
    user_id text NOT NULL REFERENCES career_quest.app_users(id) ON DELETE CASCADE,
    csrf text NOT NULL,
    expires_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS career_quest.login_attempts (
    host text PRIMARY KEY,
    count integer NOT NULL,
    until_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS employees_manager ON career_quest.employees(manager_id);
CREATE INDEX IF NOT EXISTS history_employee_date ON career_quest.activity_history(employee_id, date);
CREATE INDEX IF NOT EXISTS requests_employee_status ON career_quest.requests(employee_id, status);
CREATE INDEX IF NOT EXISTS audits_employee_at ON career_quest.audit_log(employee_id, at);
CREATE INDEX IF NOT EXISTS recommendations_employee_at ON career_quest.recommendations(employee_id, at);
CREATE INDEX IF NOT EXISTS sessions_expiry ON career_quest.sessions(expires_at);

-- No browser role receives access to personnel, credentials, or sessions.
-- The connection owner bypasses RLS; all user-level checks remain in Go.
DO $security$
DECLARE t record; r text;
BEGIN
    FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'career_quest' LOOP
        EXECUTE format('ALTER TABLE career_quest.%I ENABLE ROW LEVEL SECURITY', t.tablename);
        EXECUTE format('REVOKE ALL ON career_quest.%I FROM PUBLIC', t.tablename);
    END LOOP;
    FOREACH r IN ARRAY ARRAY['anon', 'authenticated', 'service_role'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
            EXECUTE format('REVOKE ALL ON SCHEMA career_quest FROM %I', r);
            EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA career_quest FROM %I', r);
        END IF;
    END LOOP;
END
$security$;
COMMIT;

-- Source: backend/migrations/002_agent.sql
BEGIN;
CREATE TABLE IF NOT EXISTS career_quest.agent_runs (
    sort_order integer NOT NULL UNIQUE,
    id text PRIMARY KEY,
    employee_id text NOT NULL REFERENCES career_quest.employees(employee_id) DEFERRABLE INITIALLY DEFERRED,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    status text NOT NULL CHECK (status IN ('draft', 'applied', 'cancelled', 'no_match')),
    trigger text NOT NULL DEFAULT 'manual',
    mode text NOT NULL CHECK (mode IN ('llm', 'planner')),
    model text NOT NULL,
    warning text NOT NULL,
    input jsonb NOT NULL,
    input_hash text NOT NULL,
    signature text NOT NULL,
    target jsonb NOT NULL,
    summary text NOT NULL,
    steps jsonb NOT NULL,
    progress_before integer NOT NULL CHECK (progress_before BETWEEN 0 AND 100),
    progress_after integer NOT NULL CHECK (progress_after BETWEEN 0 AND 100),
    projected_gaps jsonb NOT NULL,
    total_hours double precision NOT NULL,
    existing_hours double precision NOT NULL,
    trace jsonb NOT NULL,
    artifacts jsonb NOT NULL,
    duration_ms bigint NOT NULL
);
ALTER TABLE career_quest.agent_runs ADD COLUMN IF NOT EXISTS trigger text NOT NULL DEFAULT 'manual';
CREATE TABLE IF NOT EXISTS career_quest.agent_watches (
    sort_order integer NOT NULL UNIQUE,
    employee_id text PRIMARY KEY REFERENCES career_quest.employees(employee_id),
    enabled boolean NOT NULL,
    constraints jsonb NOT NULL,
    signature text NOT NULL,
    last_run_id text NOT NULL,
    status text NOT NULL,
    claim text NOT NULL,
    lease_until text NOT NULL,
    updated_at text NOT NULL,
    reason text NOT NULL
);
ALTER TABLE career_quest.agent_watches ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON career_quest.agent_watches FROM PUBLIC;
CREATE UNIQUE INDEX IF NOT EXISTS agent_runs_idempotency ON career_quest.agent_runs(employee_id, (input->>'idempotency_key'));
CREATE INDEX IF NOT EXISTS agent_runs_employee_at ON career_quest.agent_runs(employee_id, created_at);
ALTER TABLE career_quest.agent_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON career_quest.agent_runs FROM PUBLIC;
DO $security$
DECLARE r text;
BEGIN
    FOREACH r IN ARRAY ARRAY['anon', 'authenticated', 'service_role'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
            EXECUTE format('REVOKE ALL ON career_quest.agent_runs FROM %I', r);
            EXECUTE format('REVOKE ALL ON career_quest.agent_watches FROM %I', r);
        END IF;
    END LOOP;
END
$security$;
COMMIT;

-- Source: backend/migrations/003_courses.sql
-- Additive migration. Apply after 001_supabase.sql (or the complete initial export).
BEGIN;
CREATE TABLE IF NOT EXISTS career_quest.courses (
 sort_order integer NOT NULL UNIQUE,
 event_id text PRIMARY KEY REFERENCES career_quest.events(event_id) DEFERRABLE INITIALLY DEFERRED,
 pass_score integer NOT NULL CHECK (pass_score BETWEEN 1 AND 100),
 lessons jsonb NOT NULL CHECK (jsonb_typeof(lessons) = 'array'),
 questions jsonb NOT NULL CHECK (jsonb_typeof(questions) = 'array')
);
CREATE TABLE IF NOT EXISTS career_quest.course_progress (
 sort_order integer NOT NULL UNIQUE,
 id text PRIMARY KEY,
 request_id text NOT NULL UNIQUE REFERENCES career_quest.requests(id) DEFERRABLE INITIALLY DEFERRED,
 completed_lessons jsonb NOT NULL,
 updated_at text NOT NULL
);
CREATE TABLE IF NOT EXISTS career_quest.course_uploads (
 sort_order integer NOT NULL UNIQUE,
 id text PRIMARY KEY,
 request_id text NOT NULL REFERENCES career_quest.requests(id) DEFERRABLE INITIALLY DEFERRED,
 question_id text NOT NULL,
 name text NOT NULL,
 content text NOT NULL CHECK (octet_length(content) BETWEEN 1 AND 65536),
 size integer NOT NULL CHECK (size BETWEEN 1 AND 65536),
 created_at text NOT NULL
);
CREATE TABLE IF NOT EXISTS career_quest.exam_attempts (
 sort_order integer NOT NULL UNIQUE,
 id text PRIMARY KEY,
 request_id text NOT NULL REFERENCES career_quest.requests(id) DEFERRABLE INITIALLY DEFERRED,
 idempotency_key text NOT NULL,
 created_at text NOT NULL,
 updated_at text NOT NULL,
 status text NOT NULL CHECK (status IN ('submitted', 'grading', 'graded', 'grading_failed')),
 answers jsonb NOT NULL,
 grades jsonb,
 score integer NOT NULL CHECK (score BETWEEN 0 AND 100),
 passed boolean NOT NULL,
 feedback text NOT NULL,
 model text NOT NULL,
 lease text NOT NULL,
 UNIQUE(request_id, idempotency_key),
 CHECK (NOT passed OR (status = 'graded'))
);
CREATE UNIQUE INDEX IF NOT EXISTS exams_one_pending ON career_quest.exam_attempts(request_id) WHERE status <> 'graded';
CREATE UNIQUE INDEX IF NOT EXISTS exams_one_pass ON career_quest.exam_attempts(request_id) WHERE passed;
CREATE INDEX IF NOT EXISTS course_uploads_request ON career_quest.course_uploads(request_id);
CREATE INDEX IF NOT EXISTS exams_request ON career_quest.exam_attempts(request_id);
-- App sessions are server-owned; browser roles must never read answer keys or uploads.
DO $security$
DECLARE t text; r text;
BEGIN
 FOREACH t IN ARRAY ARRAY['courses', 'course_progress', 'course_uploads', 'exam_attempts'] LOOP
  EXECUTE format('ALTER TABLE career_quest.%I ENABLE ROW LEVEL SECURITY', t);
  EXECUTE format('REVOKE ALL ON career_quest.%I FROM PUBLIC', t);
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated', 'service_role'] LOOP
   IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
    EXECUTE format('REVOKE ALL ON career_quest.%I FROM %I', t, r);
   END IF;
  END LOOP;
 END LOOP;
END
$security$;
COMMIT;
