'use client';
import { useI18n } from '../lib/i18n';

import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowLeft, Check, CheckCircle, Plus, X, CalendarBlank, Clock, UsersThree, BookOpen, Sparkle, Eye, MagnifyingGlass, FloppyDisk, WarningCircle } from '@phosphor-icons/react';
import { Btn } from './UI';
import { AppBadge, ActivityBadges } from './AppBadge';
import { type Workspace, typeName, formatName } from '../lib/types';
import { grades, type HREvent, type HRCall } from '../lib/hr';
import s from './HRWorkspace.module.css';

type Skill = {skill_id:string;name:string};
const blank = ():HREvent=>({event_id:`EV_HR_${crypto.randomUUID()}`,title:'',description:'',type:'workshop',format:'online',duration_hours:4,mandatory:false,target_roles:[],target_grades:[],develops_skills:[],prerequisites:{},upcoming_sessions:[]});
export default function HREventBuilder({data,call,refresh}:{data:Workspace;call:HRCall;refresh:()=>Promise<void>}) {
 const { t, date, number, count, languageTag } = useI18n();

  const [event,setEvent]=useState<HREvent|null>(null),[step,setStep]=useState(0),[mode,setMode]=useState<'builder'|'catalog'>('builder'),[error,setError]=useState(''),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState(''),[query,setQuery]=useState('');
  const [skillID,setSkillID]=useState(''),[prereqID,setPrereqID]=useState(''),[session,setSession]=useState('');
  const form=useRef<HTMLFormElement>(null);const key=`career-quest-hr-event-${data.user.id}`;
  const roles=[...new Set(data.roles.map(r=>r.role))];const skills:Skill[]=(data as Workspace & {skills?:Skill[]}).skills||[];
  useEffect(()=>{setEvent(blank());},[]);
  function update(patch:Partial<HREvent>){setEvent(e=>e?{...e,...patch}:e);setError('');setSaved('');setSuccess('');}
  function saveDraft(){if(!event)return;try{localStorage.setItem(key,JSON.stringify(event));setSaved(t("Черновик сохранён в этом браузере"));}catch{setError('Браузер не разрешил сохранить черновик. Оставьте форму открытой.');}}
  function restoreDraft(){try{const raw=localStorage.getItem(key);if(!raw){setSaved(t("Сохранённого черновика пока нет"));return;}const d=JSON.parse(raw);if(!d.event_id?.startsWith('EV_HR_')||!Array.isArray(d.target_roles)||!Array.isArray(d.target_grades)||!Array.isArray(d.develops_skills)||!Array.isArray(d.upcoming_sessions)||!d.prerequisites||typeof d.title!=='string'||typeof d.description!=='string')throw new Error();setEvent({...blank(),...d});setStep(0);setSaved(t("Черновик восстановлен"));setError('');setSuccess('');}catch{setError('Черновик не удалось прочитать. Создайте новое событие.');}}
  function next(){if(!form.current?.reportValidity())return;if(step===1&&(!event?.target_roles.length||!event.target_grades.length)){setError('Выберите хотя бы одну роль и один грейд.');return;}setError('');setStep(v=>Math.min(3,v+1));}
  async function publish(){if(!event||busy)return;setBusy(true);setError('');try{await call('hr/events',event);const title=event.title;try{localStorage.removeItem(key);}catch{}setEvent(blank());setStep(0);setSuccess(t("«{0}» опубликовано. Событие доступно в каталоге.", { 0: title }));setSaved('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!event)return null;
  const audience=data.roster.filter(p=>event.target_roles.includes(p.role)&&event.target_grades.includes(p.grade));
  const toggle=(field:'target_roles'|'target_grades',value:string)=>update({[field]:event[field].includes(value)?event[field].filter(v=>v!==value):[...event[field],value]});
  const catalog=data.events.filter(e=>`${e.title} ${t(e.title)} ${t(e.description)}`.toLowerCase().includes(query.toLowerCase()));
  return <div className={s.root}>
    <div className={s.heading}><div><h1>{t("Место для нового опыта.")}</h1><p>{t("Создавайте события, которые превращают интерес в навыки.")}</p></div><div className={s.segment}><button aria-pressed={mode==='builder'} onClick={()=>setMode('builder')}>{t("Конструктор")}</button><button aria-pressed={mode==='catalog'} onClick={()=>setMode('catalog')}>{t("Каталог ·")} {data.events.length}</button></div></div>
    {success&&<div className={s.success} role="status"><CheckCircle size={21}/>{t(success)}<button onClick={()=>setSuccess('')} aria-label={t("Закрыть уведомление")}><X size={18}/></button></div>}
    {mode==='catalog'?<><label className={s.search}><MagnifyingGlass size={18}/><input aria-label={t("Поиск событий HR")} placeholder={t("Найти событие")} value={query} onChange={e=>setQuery(e.target.value)}/></label><div className={s.catalogGrid}>{catalog.map(ev=><article className={s.card} key={ev.event_id}><ActivityBadges event={ev}/><h2 className={s.catalogTitle}>{t(ev.title)}</h2><p className={s.note}>{t(ev.description)}</p><div className={s.catalogFoot}><span>{ev.mandatory?t("Обязательное обучение"):t("{0} навыков", { 0: ev.develops_skills?.length||0 })}</span><Btn variant="ghost" onClick={()=>{setEvent({...blank(),...ev,event_id:blank().event_id,title:t("{0}: копия", { 0: ev.title }),upcoming_sessions:ev.upcoming_sessions?.filter(d=>d>=data.snapshot)||[],target_roles:(ev as HREvent).target_roles||[],target_grades:(ev as HREvent).target_grades||[],prerequisites:(ev as HREvent).prerequisites||{}});setMode('builder');setStep(0);setError('');setSuccess('');setSaved('');}}>{t("Создать копию")}<ArrowUpRightIcon/></Btn></div></article>)}</div>{!catalog.length&&<div className={s.emptyInline}>{t("Ничего не найдено. Попробуйте другое название.")}</div>}</>:<>
    <div className={s.builderTools}><span><FloppyDisk size={16}/>{t(saved)||t("Новый черновик")}</span><div><button className={s.textButton} onClick={restoreDraft} disabled={busy}>{t("Восстановить черновик")}</button><Btn onClick={saveDraft} disabled={busy}>{t("Сохранить черновик")}</Btn></div></div>
    <div className={s.builderLayout}><section className={`${s.card} ${s.builderCard}`}><ol className={s.stepper}>{[t("Основное"),t("Участники"),t("Навыки"),t("Проверка")].map((label,i)=><li key={label} aria-current={step===i?'step':undefined} className={i<=step?s.stepActive:''}><span>{i<step?<Check size={14}/>:i+1}</span><b>{label}</b></li>)}</ol>
    <form ref={form} onSubmit={e=>{e.preventDefault();if(step===3)void publish();else next();}}><fieldset disabled={busy} className={s.formFields}>
      {step===0&&<><div className={s.formIntro}><h2>{t("С чего начнём?")}</h2><p>{t("Задайте формат и объясните, что получат участники.")}</p></div><div className={s.templates}>{[{type:'workshop',label:t("Практикум"),hours:4,icon:Sparkle},{type:'course',label:t("Курс"),hours:16,icon:BookOpen},{type:'mentoring',label:t("Менторство"),hours:2,icon:UsersThree}].map(template=><button type="button" key={template.type} aria-pressed={event.type===template.type} onClick={()=>update({type:template.type,duration_hours:template.hours,mandatory:false})}><template.icon size={23}/>{t(template.label)}<small>{template.hours}  {t("ч по умолчанию")}</small></button>)}</div><label className={s.field}>{t("Название")}<input required minLength={4} maxLength={160} value={event.title} onChange={e=>update({title:e.target.value})} placeholder={t("Например, системное мышление на практике")}/></label><label className={s.field}>{t("Описание и результат")}<textarea required minLength={20} maxLength={4000} rows={4} value={event.description} onChange={e=>update({description:e.target.value})} placeholder={t("Что разберём, что попробуем и с чем уйдут участники")}/><small>{t("От 20 символов. Конкретный результат помогает сделать выбор.")}</small></label><div className={s.formRow}><label className={s.field}>{t("Тип")}<select value={event.type} onChange={e=>update({type:e.target.value,mandatory:['compliance','onboarding'].includes(e.target.value)?true:event.mandatory})}>{Object.entries(typeName).map(([v,l])=><option value={v} key={v}>{t(l)}</option>)}</select></label><label className={s.field}>{t("Формат")}<select value={event.format} onChange={e=>update({format:e.target.value,upcoming_sessions:e.target.value==='self_paced'?[]:event.upcoming_sessions})}>{Object.entries(formatName).map(([v,l])=><option value={v} key={v}>{t(l)}</option>)}</select></label><label className={s.field}>{t("Длительность, ч")}<input type="number" min={0.5} max={500} step={0.5} required value={event.duration_hours} onChange={e=>update({duration_hours:Number(e.target.value)})}/></label></div>
      {event.format!=='self_paced'&&<div className={s.field}>{t("Даты проведения")}<div className={s.inlineField}><input aria-label={t("Дата проведения")} type="date" min={data.snapshot} value={session} onChange={e=>setSession(e.target.value)}/><Btn disabled={!session||session<data.snapshot||event.upcoming_sessions.length>=30} onClick={()=>{if(!event.upcoming_sessions.includes(session))update({upcoming_sessions:[...event.upcoming_sessions,session].sort()});setSession('');}}><Plus size={16}/>{t("Добавить дату")}</Btn></div><div className={s.chips}>{event.upcoming_sessions.map(d=><span key={d}>{date(d)}<button type="button" aria-label={t("Убрать дату {0}", { 0: d })} onClick={()=>update({upcoming_sessions:event.upcoming_sessions.filter(v=>v!==d)})}><X size={13}/></button></span>)}</div>{!event.upcoming_sessions.length&&<small>{t("Добавьте хотя бы одну дату, начиная с 1 октября 2026.")}</small>}</div>}</>}
      {step===1&&<><div className={s.formIntro}><h2>{t("Для кого это событие?")}</h2><p>{t("Роли и грейды определяют, кому доступно участие.")}</p></div><div className={s.field}>{t("Роли")}<div className={s.checkboxGrid}>{roles.map(role=><label key={role}><input type="checkbox" checked={event.target_roles.includes(role)} onChange={()=>toggle('target_roles',role)}/>{role}</label>)}</div></div><div className={s.field}>{t("Грейды")}<div className={s.gradeChoices}>{grades.map(g=><button type="button" key={g} aria-pressed={event.target_grades.includes(g)} onClick={()=>toggle('target_grades',g)}>{event.target_grades.includes(g)&&<Check size={15}/>} {g}</button>)}</div></div><label className={s.checkLine}><input type="checkbox" checked={event.mandatory} disabled={['compliance','onboarding'].includes(event.type)} onChange={e=>update({mandatory:e.target.checked})}/><span><b>{t("Обязательное обучение")}</b><small>{t("Исключается из добровольных рекомендаций. Публикация не назначает участие автоматически.")}</small></span></label><div className={s.audienceCount}><UsersThree size={28}/><strong>{audience.length}</strong><span>{t("сотрудников подходят")}<br/>{t("по роли и грейду")}</span></div></>}
      {step===2&&<><div className={s.formIntro}><h2>{t("Какие навыки вырастут?")}</h2><p>{t("Прирост применяется после завершения и подтверждения результата.")}</p></div><div className={s.inlineField}><select aria-label={t("Добавить развиваемый навык")} value={skillID} onChange={e=>setSkillID(e.target.value)}><option value="">{t("Выберите навык")}</option>{skills.filter(sk=>!event.develops_skills.some(g=>g.skill_id===sk.skill_id)).map(sk=><option key={sk.skill_id} value={sk.skill_id}>{t(sk.name)}</option>)}</select><Btn disabled={!skillID} onClick={()=>{update({develops_skills:[...event.develops_skills,{skill_id:skillID,gain:1,max_level:5}]});setSkillID('');}}><Plus size={17}/>{t("Добавить")}</Btn></div>{event.develops_skills.map(g=><div key={g.skill_id} className={s.gainEditor}><b>{t(skills.find(sk=>sk.skill_id===g.skill_id)?.name||g.skill_id)}</b><label>{t("Прирост")}<input type="number" min={1} max={g.max_level} required value={g.gain} onChange={e=>update({develops_skills:event.develops_skills.map(x=>x.skill_id===g.skill_id?{...x,gain:Number(e.target.value)}:x)})}/></label><label>{t("Предел")}<input type="number" min={g.gain} max={5} required value={g.max_level} onChange={e=>update({develops_skills:event.develops_skills.map(x=>x.skill_id===g.skill_id?{...x,max_level:Number(e.target.value)}:x)})}/></label><Btn variant="ghost" shape="square" aria-label={t("Убрать навык {0}", { 0: skills.find(sk=>sk.skill_id===g.skill_id)?.name })} onClick={()=>update({develops_skills:event.develops_skills.filter(x=>x.skill_id!==g.skill_id)})}><X size={17}/></Btn></div>)}{!event.develops_skills.length&&<p className={s.note}>{t("Для добровольного события нужен хотя бы один навык.")}</p>}<div className={s.formIntro}><h3>{t("Требования к участию")}</h3><p>{t("Необязательно. Минимальный уровень, с которым можно начать.")}</p></div><div className={s.inlineField}><select aria-label={t("Навык для требования")} value={prereqID} onChange={e=>setPrereqID(e.target.value)}><option value="">{t("Выберите навык")}</option>{skills.filter(sk=>!(sk.skill_id in event.prerequisites)).map(sk=><option key={sk.skill_id} value={sk.skill_id}>{t(sk.name)}</option>)}</select><Btn disabled={!prereqID} onClick={()=>{update({prerequisites:{...event.prerequisites,[prereqID]:1}});setPrereqID('');}}><Plus size={17}/>{t("Добавить")}</Btn></div>{Object.entries(event.prerequisites).map(([id,level])=><div className={s.gainEditor} key={id}><b>{t(skills.find(sk=>sk.skill_id===id)?.name)}</b><label>{t("Уровень")}<input type="number" required min={1} max={5} value={level} onChange={e=>update({prerequisites:{...event.prerequisites,[id]:Number(e.target.value)}})}/></label><Btn variant="ghost" shape="square" aria-label={t("Убрать требование")} onClick={()=>update({prerequisites:Object.fromEntries(Object.entries(event.prerequisites).filter(([k])=>k!==id))})}><X size={17}/></Btn></div>)}</>}
      {step===3&&<><div className={s.formIntro}><AppBadge icon={Eye} tone="green">{t("Финальная проверка")}</AppBadge><h2>{t("Готово к новым открытиям?")}</h2><p>{t("Событие появится в каталоге и будет учитываться при подборе развития.")}</p></div><div className={s.reviewRows}><div><span>{t("Название")}</span><b>{t(event.title)}</b></div><div><span>{t("Формат")}</span><b>{t(typeName[event.type])} · {t(formatName[event.format])} · {event.duration_hours}  {t("ч")}</b></div><div><span>{t("Аудитория")}</span><b>{event.target_roles.join(', ')}<small>{event.target_grades.join(' · ')}</small></b></div><div><span>{t("Дата")}</span><b>{event.format==='self_paced'?t("В любое время"):event.upcoming_sessions.map(value=>date(value)).join(', ')||t("Не выбрана")}</b></div><div><span>{t("Навыки")}</span><b>{event.develops_skills.length}  {t("развиваемых ·")} {Object.keys(event.prerequisites).length}  {t("требований")}</b></div></div><div className={s.modelNote}><CheckCircle size={20}/><p>{t("Участники выбирают событие через обычный процесс согласования. Навыки и грейды сотрудников сейчас не изменятся.")}</p></div></>}
    </fieldset>{error&&<div className={s.formError} role="alert"><WarningCircle size={18}/>{t(error)}</div>}<div className={s.formActions}><Btn disabled={step===0||busy} onClick={()=>{setStep(v=>v-1);setError('');}}><ArrowLeft size={16}/>{t("Назад")}</Btn><span>{step+1} / 4</span><Btn variant="primary" type="submit" disabled={busy||(step===0&&event.format!=='self_paced'&&!event.upcoming_sessions.length)||(step===2&&!event.mandatory&&!event.develops_skills.length)} loading={busy}>{step===3?t("Опубликовать событие"):t("Продолжить")}{step===3?<Check size={17}/>:<ArrowRight size={17}/>}</Btn></div></form></section>
    <aside className={s.previewColumn}><div className={s.previewLabel}><Eye size={16}/>{t("ТАК УВИДЯТ СОТРУДНИКИ")}</div><article className={`${s.card} ${s.eventPreview}`}><div className={s.previewArt} aria-hidden="true"><div className={s.staircase}>{[1,2,3,4,5].map(n=><i key={n} style={{height:n*22}}/>)}</div><Sparkle size={48} weight="thin"/></div><div className={s.previewBody}><AppBadge icon={BookOpen} tone="green">{t(typeName[event.type])}</AppBadge><h2>{event.title||t("Здесь начинается новый навык")}</h2><p>{event.description||t("Добавьте описание: чему научатся участники и как это поможет в работе.")}</p><div className={s.previewMeta}><span><Clock size={16}/>{event.duration_hours}  {t("ч")}</span><span><CalendarBlank size={16}/>{t(formatName[event.format])}</span></div>{event.develops_skills.length>0&&<div className={s.previewSkills}>{event.develops_skills.map(g=><div key={g.skill_id}><span>{t(skills.find(sk=>sk.skill_id===g.skill_id)?.name)}</span><b>+{g.gain}<small>{t("до")} {g.max_level}</small></b></div>)}</div>}<div className={s.previewFooter}>{event.mandatory?t("Обязательное обучение"):event.format==='self_paced'?t("Можно начать в любое время"):event.upcoming_sessions[0]?date(event.upcoming_sessions[0]):t("Дата пока не выбрана")}<ArrowRight size={17}/></div></div></article><p className={s.previewHint}>{t("Предпросмотр обновляется по мере заполнения. Сохраните черновик, чтобы вернуться к нему позже.")}</p></aside></div></>}
  </div>;
}
function ArrowUpRightIcon(){return <ArrowRight size={15}/>;}
