'use client';
import { useI18n } from '../lib/i18n';

import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowsClockwise, Check, CheckCircle, Clock, DownloadSimple, Flask, Info, Plus, Target, Trash, WarningCircle } from '@phosphor-icons/react';
import { Btn } from './UI';
import { AppBadge, ActivityBadges } from './AppBadge';
import { LoadingStatus } from './Feedback';
import type { Workspace } from '../lib/types';
import { download, grades, type HRCall, type Simulation } from '../lib/hr';
import { Ring } from './HRWorkspace';
import s from './HRWorkspace.module.css';

export default function HRSimulator({data,call}:{data:Workspace;call:HRCall}) {
 const { t, date, number, count, languageTag } = useI18n();

  const initial=data.roster.find(p=>p.grade==='Middle')||data.roster[0];
  const [employee,setEmployee]=useState(initial?.employee_id||''),[role,setRole]=useState(initial?.role||''),[grade,setGrade]=useState(initial?grades[Math.min(3,grades.indexOf(initial.grade)+1)]:'Senior');
  const [weeks,setWeeks]=useState(12),[hours,setHours]=useState(4),[ids,setIDs]=useState<string[]>([]),[result,setResult]=useState<Simulation|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[showBlocked,setShowBlocked]=useState(false);
  const request=useRef(0),plan=useRef<string[]>([]);const person=data.roster.find(p=>p.employee_id===employee);
  async function calculate(next:string[],clearOnError=false) {
    if(!employee)return;const id=++request.current;setBusy(true);setError('');
    try{const r=await call('hr/simulate',{employee_id:employee,target_role:role,target_grade:grade,weeks,hours_per_week:hours,event_ids:next});if(request.current===id){setResult(r);setIDs(next);plan.current=next;}}
    catch(e){if(request.current===id){setError((e as Error).message);if(clearOnError)setResult(null);}}
    finally{if(request.current===id)setBusy(false);}
  }
  useEffect(()=>{void calculate(plan.current,true);return()=>{request.current++;};},[employee,role,grade,weeks,hours,call,data]);
  function resetPlan(){plan.current=[];setIDs([]);setResult(null);setError('');}
  function exportPlan(){if(!result||!person)return;download(`grade-scenario-${employee}.md`,[
    t("# Сценарий развития: {0}", { 0: person.full_name }),t("Дата среза: {0}", { 0: data.snapshot }),t("Текущая роль: {0} / {1}", { 0: person.role, 1: person.grade }),t("Цель: {0} / {1}", { 0: role, 1: grade }),t("Нагрузка: {0} ч/нед., горизонт: {1} недель", { 0: hours, 1: weeks }),
    t("Соответствие требованиям: {0}% → {1}%", { 0: result.before, 1: result.after }), t("Объём: {0} ч. Оценка срока: {1} недель. В пределах горизонта: {2}.", { 0: result.hours, 1: result.required_weeks, 2: result.feasible?'да':'нет' }),
    t("\n## Активности"),...ids.map((id,i)=>`${i+1}. ${t(data.events.find(e=>e.event_id===id)?.title||id)}`), t("\n## Навыки"),...result.skills.map(sk=>t("- {0}: {1} → {2}; требуется {3}{4}", { 0: sk.name, 1: sk.before, 2: sk.after, 3: sk.required, 4: sk.critical?' (критический)':'' })),
    t("\nРасчётный сценарий предполагает успешное завершение выбранных активностей. Срок учитывает часы и ожидание сессий, но не текущую рабочую нагрузку. Это не решение о повышении. Профиль и грейд не изменены.")
  ].join('\n'));}
  const options=result?.options.filter(o=>showBlocked||!o.blocked)||[];
  if(!initial)return <div className={s.emptyInline}>{t("Для моделирования сначала добавьте сотрудников.")}</div>;
  return <div className={s.root}><div className={s.heading}><div><div className={s.eyebrow}><span/> CAREER LAB / WHAT IF</div><h1>{t("А что, если следующий грейд?")}</h1><p>{t("Соберите сценарий развития и посмотрите, что изменится.")}</p></div><Btn onClick={exportPlan} disabled={!result||busy}><DownloadSimple size={17}/>{t("Скачать сценарий")}</Btn></div>
    <div className={s.simulatorControls}><label className={s.field}>{t("Сотрудник")}<select aria-label={t("Сотрудник для моделирования")} value={employee} onChange={e=>{const p=data.roster.find(p=>p.employee_id===e.target.value)!;resetPlan();setEmployee(p.employee_id);setRole(p.role);setGrade(grades[Math.min(3,grades.indexOf(p.grade)+1)]);}}>{data.roster.map(p=><option value={p.employee_id} key={p.employee_id}>{p.full_name} · {t(p.grade)}</option>)}</select></label><label className={s.field}>{t("Целевая роль")}<select value={role} onChange={e=>{resetPlan();setRole(e.target.value);}}>{[...new Set(data.roles.map(r=>r.role))].map(r=><option key={r} value={r}>{t(r)}</option>)}</select></label><label className={s.field}>{t("Целевой грейд")}<select value={grade} onChange={e=>{resetPlan();setGrade(e.target.value);}}>{data.roles.filter(r=>r.role===role).map(r=><option key={r.grade} value={r.grade}>{t(r.grade)}</option>)}</select></label></div>
    <div className={s.simLayout}><section className={s.simMain}><div className={`${s.card} ${s.scenarioCard}`}><div className={s.sectionHeading}><div><AppBadge icon={Flask} tone="purple">{t("Расчётный сценарий")}</AppBadge><h2 className={s.transition}>{t(person?.grade)}<ArrowRight size={22}/><span>{t(grade)}</span></h2><p className={s.note}>{person?.full_name} · {role}</p></div><Target size={42} weight="thin"/></div><div className={s.sliders}><label>{t("Время на развитие")} <strong>{number(hours)} {t("ч / нед.")}</strong><input type="range" min={1} max={16} value={hours} onChange={e=>setHours(Number(e.target.value))}/><span><small>{t("1 час")}</small><small>{t("16 часов")}</small></span></label><label>{t("Горизонт планирования")} <strong>{weeks}  {t("нед.")}</strong><input type="range" min={2} max={52} step={1} value={weeks} onChange={e=>setWeeks(Number(e.target.value))}/><span><small>{t("2 недели")}</small><small>{t("1 год")}</small></span></label></div></div>
    <section className={s.card}><div className={s.sectionHeading}><div><h2>{t("Шаги к новой роли")}</h2><p className={s.note}>{t("Добавляйте активности в порядке прохождения.")}</p></div><span className={s.countBadge}>{ids.length} / 20</span></div>{ids.length>0?<ol className={s.planList}>{ids.map((id,i)=>{const ev=data.events.find(e=>e.event_id===id);return <li key={id}><span>{i+1}</span><div><b>{t(ev?.title)}</b><small>{ev?.duration_hours}  {t("ч · навыки после подтверждения")}</small></div><Btn variant="ghost" shape="square" disabled={busy} aria-label={t("Убрать {0}", { 0: ev?.title })} onClick={()=>void calculate(ids.filter(x=>x!==id))}><Trash size={17}/></Btn></li>;})}</ol>:<div className={s.planEmpty}><Plus size={22}/><p>{t("Выберите первый шаг из подходящих активностей ниже.")}</p></div>}
    {error&&<div className={s.formError} role="alert"><WarningCircle size={18}/><span>{t(error)}</span><Btn onClick={()=>void calculate([])}>{t("Сбросить")}</Btn></div>}
    <div className={s.sectionHeading}><h3>{t("Подходящие активности")}</h3><label className={s.inlineCheckbox}><input type="checkbox" checked={showBlocked} onChange={e=>setShowBlocked(e.target.checked)}/>{t("С ограничениями")}</label></div>
    {busy?<div className={s.loading}><LoadingStatus label={t("Пересчитываем сценарий…")}/></div>:options.length?<div className={s.simOptions}>{options.map(o=><article key={o.event.event_id}><div><ActivityBadges event={o.event}/><h3>{t(o.event.title)}</h3>{o.blocked?<p className={s.blocked}>{o.blocked}</p>:<p className={s.note}>{t("Закроет")} {o.gain}  {t("ур. разрыва по целевым навыкам")}</p>}</div><Btn shape="square" disabled={!!o.blocked||ids.length>=20} aria-label={t("Добавить {0}", { 0: o.event.title })} onClick={()=>void calculate([...ids,o.event.event_id])}><Plus size={19}/></Btn></article>)}</div>:<div className={s.emptyInline}>{result?.after===100?t("Требования к навыкам уже выполнены. Обсудите следующий шаг с руководителем."):t("Нет доступных активностей для оставшихся разрывов. Проверьте ограничения или создайте новое событие.")}</div>}
    {ids.length>0&&<button className={s.textButton} disabled={busy} onClick={()=>void calculate([])}><ArrowsClockwise size={15}/>{t("Очистить сценарий")}</button>}</section></section>
    <aside className={s.simResults} aria-busy={busy}><section className={`${s.card} ${s.projectionCard}`}><div className={s.sectionHeading}><h2>{t("Эффект сценария")}</h2><span className={s.liveLabel}><span/>{busy?t("Расчёт…"):t("Прогноз")}</span></div>{result?<><Ring value={result.before} secondary={result.after} label={t("готовность к цели")}/><div className={s.beforeAfter}><span>{t("Сейчас")} <b>{result.before}%</b></span><ArrowRight size={18}/><span>{t("После")} <b>{result.after}%</b></span></div><div className={s.projectionStats}><div><span>{t("Прирост")}</span><b>+{result.after-result.before}  {t("п.п.")}</b></div><div><span>{t("Объём обучения")}</span><b>{result.hours}  {t("ч")}</b></div><div><span>{t("Оценка срока")}</span><b>{result.required_weeks?t("{0} нед.", { 0: result.required_weeks }):'—'}</b></div><div><span>{t("Критических разрывов")}</span><b>{result.critical_gaps}</b></div></div>{ids.length>0&&<div className={`${s.feasibility} ${!result.feasible?s.overBudget:''}`}>{result.feasible?<CheckCircle size={19}/>:<WarningCircle size={19}/>}<span>{result.feasible?t("Укладывается в выбранный горизонт"):t("Нужно не менее {0} недель", { 0: result.required_weeks })}</span></div>}<p className={s.note}>{t("Срок учитывает последовательное прохождение и ожидание сессий. Текущая рабочая нагрузка не включена.")}</p></>:<div className={s.loading}>{error?<p className={s.note}>{t("Не удалось рассчитать сценарий. Повторите запрос.")}</p>:<LoadingStatus label={t("Оцениваем исходные навыки…")}/>}</div>}</section>
    <div className={s.modelNote}><Info size={19}/><p>{t("Модель предполагает успешное завершение всех шагов. Соответствие навыков не гарантирует повышение; грейд и профиль не изменяются.")}</p></div></aside></div>
    {result&&<section className={s.card}><div className={s.sectionHeading}><div><h2>{t("Как изменятся навыки")}</h2><p className={s.note}>{t("Текущий уровень → после сценария · шкала от 0 до 5")}</p></div><div className={s.legend}><span><i/>{t("Сейчас")}</span><span><i className={s.lime}/>{t("Прирост")}</span></div></div><div className={s.simSkillGrid}>{result.skills.map(sk=><div className={s.simSkill} key={sk.id}><div><b>{t(sk.name)}</b>{sk.critical&&<span className={s.criticalTag}>{t("Критический")}</span>}<strong>{sk.before}<ArrowRight size={12}/>{sk.after}<small>/ {sk.required}</small>{sk.after>=sk.required&&<Check size={14}/>}</strong></div><div className={s.skillSegments} role="img" aria-label={t("{0}: {1}, после {2}, нужно {3}", { 0: sk.name, 1: sk.before, 2: sk.after, 3: sk.required })}>{[1,2,3,4,5].map(n=><i key={n} className={n<=sk.before?s.segmentCurrent:n<=sk.after?s.segmentGain:n<=sk.required?s.segmentNeeded:''}/>)}</div></div>)}</div></section>}
  </div>;
}
