'use client';
import { useI18n } from '../lib/i18n';

import { useEffect, useState, useMemo } from 'react';
import { ArrowUpRight, ArrowRight, ChartBar, UsersThree, Pulse, Target, DownloadSimple, Plus, CalendarBlank, CheckCircle, Info, MagnifyingGlass, WarningCircle, ArrowLeft, TrendUp, Clock, SlidersHorizontal } from '@phosphor-icons/react';
import { Btn } from './UI';
import { AppBadge } from './AppBadge';
import { EmptyState, LoadingStatus } from './Feedback';
import HREventBuilder from './HREventBuilder';
import HRSimulator from './HRSimulator';
import type { Workspace } from '../lib/types';
import { date } from '../lib/types';
import { bands, exportCSV, type HRCall, type HRInsights, type HRPerson, type HRView } from '../lib/hr';
import s from './HRWorkspace.module.css';

export function PixelGrid({values, tone='green'}:{values:number[];tone?:'green'|'amber'|'purple'}) {
  return <div className={`${s.pixelGrid} ${s[tone]}`} aria-hidden="true">{values.map((value,i)=><i key={i} data-level={Math.min(4,Math.max(0,value))}/>)}</div>;
}
export function Ring({value,label,secondary}:{value:number;label:string;secondary?:number}) {
 const { t, date, number, languageTag } = useI18n();

  return <div className={s.ring} role="img" aria-label={`${label}: ${value}%${secondary===undefined?'':t(", после: {0}%", { 0: secondary })}`}><svg viewBox="0 0 160 160" aria-hidden="true"><circle cx="80" cy="80" r="66" className={s.ringTrack}/>{secondary!==undefined&&<circle cx="80" cy="80" r="66" className={s.ringProjection} strokeDasharray={`${secondary*4.147} 415`}/>}<circle cx="80" cy="80" r="66" className={s.ringValue} strokeDasharray={`${value*4.147} 415`}/></svg><span><strong>{secondary??value}<small>%</small></strong><small>{label}</small></span></div>;
}
function RiskBadge({band}:{band:HRPerson['band']}) { const { t } = useI18n(); return <span className={`${s.riskBadge} ${s[band]}`}><i/>{t(bands[band])}</span>; }

export default function HRWorkspace({view,data,call,refresh,navigate}:{view:HRView;data:Workspace;call:HRCall;refresh:()=>Promise<void>;navigate:(v:HRView)=>void}) {
 const { t, date, number, languageTag } = useI18n();

  const [days,setDays]=useState('90'),[department,setDepartment]=useState(''),[insights,setInsights]=useState<HRInsights|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true),[retry,setRetry]=useState(0);
  const [search,setSearch]=useState(''),[band,setBand]=useState(''),[selected,setSelected]=useState<string|null>(null);
  const departments=[...new Set(data.roster.map(e=>e.department))].sort();
  useEffect(()=>{
    if(view==='events'||view==='simulation')return;
    let active=true;setBusy(true);setError('');
    call(`hr/insights?days=${days}&department=${encodeURIComponent(department)}`).then(result=>{if(active)setInsights(result);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});
    return()=>{active=false;};
  },[call,days,department,retry,data,view]);
  const people=insights?.people||[];
  const filtered=useMemo(()=>people.filter(p=>(!band||p.band===band)&&`${p.full_name} ${p.role} ${p.department} ${t(p.role)} ${t(p.department)}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.score-a.score||a.full_name.localeCompare(b.full_name)),[people,band,search,t]);
  const person=people.find(p=>p.employee_id===selected);
  function exportPeople(){exportCSV(`hr-${view}-${days}d.csv`,[[t("Сотрудник"),t("Подразделение"),t("Роль"),t("Грейд"),t("Готовность, %"),t("Индекс внимания (не вероятность)"),t("Уровень"),t("Завершено за период"),t("Часы за период")],...(view==='risk'?filtered:people).map(p=>[p.full_name,p.department,p.role,p.grade,p.progress,p.band==='unknown'?'':p.score,bands[p.band],p.completed,p.hours])]);}
  if(view==='events')return <HREventBuilder data={data} call={call} refresh={refresh}/>;
  if(view==='simulation')return <HRSimulator data={data} call={call}/>;
  return <div className={s.root}>
    <div className={s.heading}><div><h1>{view==='risk'?t("Замечать раньше."):t("Люди. Развитие. Результат.")}</h1><p>{view==='risk'?t("Сигналы, которые помогают вовремя начать разговор."):t("Всё, что нужно для следующего шага вашей команды.")}</p></div><Btn onClick={exportPeople} disabled={busy||!people.length}><DownloadSimple size={17}/>{t("Экспорт CSV")}</Btn></div>
    <div className={s.toolbar}><div className={s.segment} aria-label={t("Период аналитики")}>{['30','90','180'].map(v=><button type="button" key={v} aria-pressed={days===v} onClick={()=>setDays(v)}>{v}  {t("дней")}</button>)}</div><label className={s.selectLabel}><SlidersHorizontal size={17}/><select aria-label={t("Подразделение")} value={department} onChange={e=>{setDepartment(e.target.value);setSelected(null);}}><option value="">{t("Все подразделения")}</option>{departments.map(d=><option key={d} value={d}>{t(d)}</option>)}</select></label><span className={s.asOf}><CalendarBlank size={15}/>{t("Срез на 1 окт 2026")}</span></div>
    {error?<EmptyState icon={WarningCircle} tone="error" title={t("Не удалось загрузить аналитику")} description={t(error)} action={<Btn onClick={()=>setRetry(v=>v+1)}>{t("Повторить")}</Btn>}/>:busy?<div className={s.loading}><LoadingStatus label={t("Собираем картину развития…")}/></div>:!people.length?<EmptyState icon={UsersThree} title={t("В этом подразделении пока нет сотрудников")} description={t("Выберите другое подразделение или добавьте профили через раздел «Доступ и данные».")}/>:view==='dashboard'?<Dashboard insights={insights!} data={data} navigate={navigate} onRisk={()=>{setBand('high');navigate('risk');}}/>:<>
      <div className={s.modelNote}><Info size={19}/><p><b>{t("Индекс внимания, а не вероятность увольнения.")}</b>  {t("Правила учитывают учебную активность за 90 дней, цель и давность оценки. Истории увольнений в данных нет. Используйте сигналы для разговора, а не кадрового решения. Выбранный период меняет статистику обучения, но не окно индекса.")}</p></div>
      <div className={s.riskSummary}>{(['high','medium','low','unknown'] as const).map(b=><button key={b} className={`${s.riskTile} ${band===b?s.riskTileActive:''}`} onClick={()=>setBand(band===b?'':b)} aria-pressed={band===b}><RiskBadge band={b}/><strong>{people.filter(p=>p.band===b).length}</strong><span>{b==='high'?t("Приоритет для разговора"):b==='medium'?t("Стоит уделить внимание"):b==='low'?t("Меньше сигналов"):t("Менее 3 записей истории")}</span></button>)}</div>
      <div className={s.riskLayout}><section className={s.card}><div className={s.sectionHeading}><h2>{t("В фокусе внимания")} <span>{filtered.length}</span></h2>{band&&<button className={s.textButton} onClick={()=>setBand('')}>{t("Все уровни")}</button>}</div><label className={s.search}><MagnifyingGlass size={18}/><input aria-label={t("Поиск сотрудника")} placeholder={t("Имя, роль или подразделение")} value={search} onChange={e=>setSearch(e.target.value)}/></label><div className={s.personList}>{filtered.slice(0,60).map(p=><button className={`${s.personRow} ${selected===p.employee_id?s.personSelected:''}`} key={p.employee_id} onClick={()=>setSelected(p.employee_id)} aria-pressed={selected===p.employee_id}><span className={s.initials}>{p.full_name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><span className={s.personName}><b>{p.full_name}</b><small>{t(p.department)} · {t(p.grade)}</small></span><span className={s.personScore}><b>{p.band==='unknown'?t("н/д"):p.score}<small>/100</small></b><RiskBadge band={p.band}/></span><ArrowUpRight size={17}/></button>)}{!filtered.length&&<div className={s.emptyInline}>{t("Совпадений нет. Измените запрос или уровень риска.")}</div>}</div>{filtered.length>60&&<p className={s.note}>{t("Показаны первые 60. Уточните поиск или экспортируйте весь список.")}</p>}</section>
      <aside className={`${s.card} ${s.factorCard}`}>{person?<><div className={s.sectionHeading}><button className={s.textButton} onClick={()=>setSelected(null)} aria-label={t("Закрыть карточку сотрудника")}><ArrowLeft size={18}/></button></div><h2>{person.full_name}</h2><p className={s.note}>{t(person.role)} · {t(person.grade)}</p><div className={s.factorScore}><strong>{person.band==='unknown'?t("н/д"):person.score}<small>/100</small></strong><RiskBadge band={person.band}/></div>{person.factors.length?person.factors.map(f=><div className={s.factor} key={t(f.label)}><div><b>{t(f.label)}</b><span>+{f.points}</span></div><p>{t(f.detail)}</p><div className={s.miniTrack}><i style={{width:`${f.points/35*100}%`}}/></div></div>):<p className={s.note}>{person.band==='unknown'?t("Недостаточно истории для индекса. Начните с уточнения целей и доступности обучения."):t("Выраженных сигналов по текущим правилам нет.")}</p>}<div className={s.suggestion}><UsersThree size={21}/><div><b>{t("Следующий шаг: личная встреча")}</b><p>{t("Обсудите нагрузку, интерес к задачам и препятствия в развитии. Уточните контекст до любых выводов.")}</p></div></div><p className={s.note}>{t("Последняя активность:")} {person.last_activity?date(person.last_activity):t("не зафиксирована")}</p></>:<div className={s.detailEmpty}><Pulse size={38} weight="thin"/><h2>{t("За цифрой стоит человек")}</h2><p>{t("Выберите сотрудника, чтобы увидеть факторы индекса и повод для разговора.")}</p><div className={s.thresholds}><span>0-29 <b>{t("Низкий")}</b></span><span>30-59 <b>{t("Умеренный")}</b></span><span>60-100 <b>{t("Высокий")}</b></span></div></div>}</aside></div>
    </>}
  </div>;
}

function Dashboard({insights,data,navigate,onRisk}:{insights:HRInsights;data:Workspace;navigate:(v:HRView)=>void;onRisk:()=>void}) {
 const { t, date, number, languageTag } = useI18n();

  const {people,trend,days}=insights;const completed=people.reduce((n,p)=>n+p.completed,0),activities=people.reduce((n,p)=>n+p.activities,0),hours=people.reduce((n,p)=>n+p.hours,0),engaged=people.filter(p=>p.engagements>0).length;
  const readiness=Math.round(people.reduce((n,p)=>n+p.progress,0)/people.length),high=people.filter(p=>p.band==='high').length,ready=people.filter(p=>p.progress===100).length;
  const ids=new Set(people.map(p=>p.employee_id));const pending=data.requests.filter(q=>ids.has(q.employee_id)&&q.status==='pending_hr').length;
  const groups=[...new Set(people.map(p=>p.department))].map(name=>{const rows=people.filter(p=>p.department===name);return {name,count:rows.length,progress:Math.round(rows.reduce((n,p)=>n+p.progress,0)/rows.length),active:rows.filter(p=>p.engagements>0).length};}).sort((a,b)=>b.progress-a.progress);
  const skillMap=new Map<string,{name:string;count:number;critical:number}>();for(const p of people)for(const g of p.gaps)if(g.current<g.required){const v=skillMap.get(g.id)||{name:g.name,count:0,critical:0};v.count++;if(g.critical)v.critical++;skillMap.set(g.id,v);}
  const skills=[...skillMap.values()].sort((a,b)=>b.count-a.count).slice(0,5);
  const buckets=Array.from({length:12},(_,i)=>{const slice=trend.slice(Math.floor(i*days/12),Math.floor((i+1)*days/12));return {date:slice[0]?.date,completed:slice.reduce((n,d)=>n+d.completed,0),other:slice.reduce((n,d)=>n+d.activities-d.completed,0)};});
  const max=Math.max(1,...buckets.map(b=>b.completed+b.other));
  return <>
    <div className={s.bento}>
      <article className={`${s.card} ${s.engagement}`}><div className={s.metricLabel}><UsersThree size={19}/><span>{t("Команда в движении")}</span><span className={s.dot}/></div><div className={s.bigNumber}>{engaged}<span>/ {people.length}</span></div><p className={s.note}>{t("участвовали в обучении за")} {days}  {t("дней")}</p><PixelGrid values={people.map(p=>p.engagements===0?0:Math.min(4,p.engagements))}/><div className={s.legend}><span><i/>{t("Есть участие")}</span><span><i className={s.inactive}/>{t("Нет активности")}</span></div></article>
      <button className={`${s.card} ${s.riskMetric}`} onClick={onRisk}><div className={s.metricLabel}><Pulse size={19}/><span>{t("Риск оттока")}</span><ArrowUpRight size={19}/></div><div className={s.bigNumber}>{high}<span>{t("чел.")}</span></div><p className={s.note}>{t("с высоким индексом внимания")}</p><div className={s.alertShape}><WarningCircle size={22} weight="fill"/>{high?t("Нужен разговор"):t("Высоких сигналов нет")}</div><span className={s.metricFoot}>{t("Объяснимые сигналы · окно 90 дней")}</span></button>
      <button className={`${s.card} ${s.readiness}`} onClick={()=>navigate('simulation')}><div className={s.metricLabel}><Target size={19}/><span>{t("Готовность к цели")}</span><ArrowUpRight size={19}/></div><Ring value={readiness} label={t("в среднем")}/><div className={s.metricFoot}><b>{ready}</b>  {t("соответствуют всем требованиям цели")}</div></button>
      <article className={`${s.card} ${s.activityCard}`}><div className={s.sectionHeading}><h2>{t("Ритм развития")}</h2><AppBadge icon={CheckCircle} tone="green">{completed}  {t("завершено")}</AppBadge></div><div className={s.chartNumbers}><strong>{number(hours)}<small>{t("ч обучения")}</small></strong><span>{activities}  {t("участий за период")}</span></div><div className={s.barChart} role="img" aria-label={t("Динамика за {0} дней: {1} завершений, {2} участий", { 0: days, 1: completed, 2: activities })} >{buckets.map((b,i)=><div key={i} className={s.barColumn} tabIndex={0} aria-label={t("{0}: {1} завершено, {2} других участий", { 0: date(b.date), 1: b.completed, 2: b.other })}><span className={s.chartTooltip}>{b.completed} / {b.completed+b.other}</span><div className={s.barStack} style={{height:`${(b.completed+b.other)/max*100}%`}}><i style={{flex:b.other}}/><b style={{flex:b.completed}}/></div></div>)}</div><div className={s.chartAxis}><span>{date(trend[0]?.date || '')}</span><span>{date(trend.at(-1)?.date || '')}</span></div><div className={s.legend}><span><i/>{t("Завершено")}</span><span><i className={s.softGreen}/>{t("Другие статусы")}</span></div></article>
      <article className={`${s.card} ${s.actionCard}`}><div className={s.metricLabel}><CalendarBlank size={19}/><span>{t("Следующий шаг")}</span></div><h2>{t("Развитие начинается")}<br/>{t("с хорошего события.")}</h2><p>{t("Соберите практикум, курс или встречу под реальные потребности команды.")}</p><div className={s.miniSchedule} aria-hidden="true"><span>{t("ОКТ")}</span><div><i>{t("Практикум")}</i><i>{t("Менторство")}</i><i>{t("Новый навык ↗")}</i></div></div><Btn variant="primary" onClick={()=>navigate('events')}><Plus size={17}/>{t("Создать событие")}</Btn></article>
    </div>
    <div className={s.bottomGrid}><section className={s.card}><div className={s.sectionHeading}><div><h2>{t("Развитие по подразделениям")}</h2><p className={s.note}>{t("Средняя готовность к индивидуальной цели")}</p></div><ChartBar size={21}/></div><div className={s.deptList}>{groups.map(g=><div key={g.name} className={s.deptRow}><div><b>{t(g.name)}</b><span>{g.count}  {t("чел. ·")} {g.active}  {t("с активностью")}</span></div><div className={s.deptProgress}><div className={s.miniTrack}><i style={{width:`${g.progress}%`}}/></div><strong>{g.progress}%</strong></div></div>)}</div></section><section className={s.card}><div className={s.sectionHeading}><div><h2>{t("Навыки для роста")}</h2><p className={s.note}>{t("Где команде нужна поддержка")}</p></div><TrendUp size={21}/></div>{skills.length?skills.map((sk,i)=><div className={s.skillDemand} key={sk.name}><span>{String(i+1).padStart(2,'0')}</span><div><b>{t(sk.name)}</b><small>{sk.critical}  {t("критических разрывов")}</small></div><strong>{sk.count}<small>{t("чел.")}</small></strong></div>):<p className={s.note}>{t("Все требования к навыкам выполнены.")}</p>}<div className={s.queueNote}><Clock size={17}/>{pending}  {t("результатов ожидают проверки HR")}</div></section></div>
  </>;
}
