'use client';
import { useEffect, useState, useCallback, useRef } from 'react';
import { Input, InputGroup } from '@cloudflare/kumo/components/input';
import { Checkbox } from '@cloudflare/kumo/components/checkbox';
import { Tabs } from '@cloudflare/kumo/components/tabs';
import HistoryPanel from '../components/HistoryPanel';
import { ArrowUpRight, ArrowRight, House, Path, SquaresFour, ClockCounterClockwise, UsersThree, ShieldCheck, SignOut, SidebarSimple, X, CaretRight, CheckCircle, Sparkle, Info, UploadSimple, Plus, MagnifyingGlass, Flag, ArrowsClockwise, CalendarBlank, UserCircle } from '@phosphor-icons/react';
import TeamPanel from '../components/TeamPanel';
import Avatar from '../components/Avatar';
import AuthStory from '../components/AuthStory';
import Home from '../components/Home';
import RequestsPanel from '../components/RequestsPanel';
import CandidateCard from '../components/CandidateCard';
import { AppBadge } from '../components/AppBadge';
import { characterIdentity } from '../lib/character';
import { EmptyState, LoadingStatus, StartupLoading, WorkspaceLoading } from '../components/Feedback';
import { ApiError, requestJSON } from '../lib/api';
import { BookOpen, Tray, WarningCircle, WifiSlash } from '@phosphor-icons/react';

import { Btn, Choice, Progress, Steps, Confirm, type ModalConfig } from '../components/UI';
import { type User, type Workspace, type Candidate, type Request, roleName } from '../lib/types';
type View='trajectory'|'catalog'|'requests'|'history'|'team'|'access'|'about';
function savedView(user:User):View {
 const available:View[]=user.role==='hr'?['team','requests','history','access','about']:user.role==='manager'?['trajectory','catalog','team','requests','history','about']:['trajectory','catalog','requests','history','about'];
 const next=location.hash.slice(1) as View;
 return available.includes(next)?next:user.role==='employee'?'trajectory':'team';
}
export default function App(){
 const[user,setUser]=useState<User|null>(null);const[csrf,setCSRF]=useState('');const[data,setData]=useState<Workspace|null>(null);const[view,setView]=useState<View>('trajectory');const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[modal,setModal]=useState<ModalConfig|null>(null);const[aiBusy,setAIBusy]=useState(false);const[search,setSearch]=useState('');const[dept,setDept]=useState('');const[catalogAll,setCatalogAll]=useState(false);
 const[sidebarCollapsed,setSidebarCollapsed]=useState(false);
 const[sessionError,setSessionError]=useState('');const[workspaceError,setWorkspaceError]=useState('');const[signingOut,setSigningOut]=useState(false);const workspaceRequest=useRef(0);
 useEffect(()=>{try{setSidebarCollapsed(localStorage.getItem('career-quest-sidebar-collapsed')==='true');}catch{}},[]);
 function toggleSidebar(){const next=!sidebarCollapsed;setSidebarCollapsed(next);try{localStorage.setItem('career-quest-sidebar-collapsed',String(next));}catch{}}
 const call=useCallback(async(path:string,payload?:unknown)=>{try{return await requestJSON(path,{method:payload===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:payload===undefined?undefined:JSON.stringify(payload)});}catch(e){if(e instanceof ApiError&&e.status===401&&path!=='login'){workspaceRequest.current++;setUser(null);setData(null);setCSRF('');setModal(null);setRefreshing(false);setError('Сессия завершилась. Войдите снова, чтобы продолжить.');}throw e;}},[csrf]);
 const refresh=useCallback(async()=>{const id=++workspaceRequest.current;setRefreshing(true);setWorkspaceError('');try{const next=await call('workspace');if(id===workspaceRequest.current)setData(next);}catch(e){if(id===workspaceRequest.current)setWorkspaceError((e as Error).message);}finally{if(id===workspaceRequest.current)setRefreshing(false);}},[call]);
 const checkSession=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setSessionError('');try{const s=await requestJSON('session',{signal});if(signal?.aborted)return;setUser(s.user);setCSRF(s.csrf);setView(savedView(s.user));}catch(e){if(signal?.aborted)return;if(!(e instanceof ApiError&&e.status===401))setSessionError((e as Error).message);}finally{if(!signal?.aborted)setLoading(false);}},[]);
 useEffect(()=>{const controller=new AbortController();void checkSession(controller.signal);return()=>controller.abort();},[checkSession]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer);},[notice]);
 useEffect(()=>{if(user)void refresh();return()=>{workspaceRequest.current++;};},[user,refresh]);
 useEffect(()=>{const onHash=()=>{if(user){setView(savedView(user));setSearch('');setError('');}};window.addEventListener('hashchange',onHash);window.addEventListener('popstate',onHash);return()=>{window.removeEventListener('hashchange',onHash);window.removeEventListener('popstate',onHash);};},[user]);
 async function act(path:string,payload:unknown,message:string){await call(path,payload);setNotice(message);setError('');void refresh();}
 function navigate(v:View){setView(v);setSearch('');setError('');if(location.hash!==`#${v}`)history.pushState(null,'',`#${v}`);window.scrollTo({top:0});}
 function choose(c:Candidate,decline=false){setModal({title:decline?'Пропустить предложение?':'Выбрать активность?',content:<><h3>{c.event.title}</h3><p>{decline?'Предложение будет скрыто.':'Заявку получит ваш руководитель.'}</p></>,sessions:!decline&&c.event.format!=='self_paced'?c.event.upcoming_sessions.filter(d=>d>=data!.snapshot):undefined,submitLabel:decline?'Пропустить':'Отправить руководителю',onConfirm:async(_,session)=>{await act('requests',{event_id:c.event.event_id,session_date:session,confirmed:true,decline},decline?'Предложение пропущено.':'Заявка отправлена.');if(!decline)navigate('requests');}});}
 function changeRequest(q:Request,action:string){const labels:Record<string,string>={approve:'Согласовать участие',reject:'Отказать',submit:'Отправить результат',complete:'Подтвердить результат',return:'Вернуть на доработку',cancel:'Отменить участие'};const event=data?.events.find(e=>e.event_id===q.event_id);setModal({title:labels[action]+'?',content:<><h3>{event?.title}</h3>{q.evidence&&<blockquote>{q.evidence}</blockquote>}{action==='complete'&&<p>Навыки обновятся после подтверждения.</p>}{['reject','return'].includes(action)&&<p>Причину увидит сотрудник.</p>}</>,note:['reject','return','complete','submit'].includes(action)?{label:action==='submit'?'Что выполнено и как проверить результат':'Причина',min:action==='submit'?20:8}:undefined,submitLabel:labels[action],onConfirm:async note=>act('transition',{id:q.id,action,note,confirmed:true},action==='complete'?'Результат подтверждён.':'Статус обновлён.')});}
 function askAI(){if(!data?.ai.available){setAIBusy(true);call('recommendations',{confirmed:true}).catch(e=>setError(e.message)).finally(()=>setAIBusy(false));return;}setModal({title:'Запросить рекомендацию Gemini?',content:<><p>Gemini получит роль, грейд, стаж, навыки, цель и данные о подходящих активностях. Имя и логин не передаются.</p><p>Используйте только данные, разрешённые для внешней передачи.</p></>,submitLabel:'Запросить рекомендации',busyLabel:'Подбираем активности…',busyDetail:'Подбор может занять до минуты.',onConfirm:async()=>{setAIBusy(true);try{await act('recommendations',{confirmed:true},'Совет сохранён.');}finally{setAIBusy(false);}}});}
 if(loading)return <StartupLoading/>;
 if(sessionError)return <main className="startup-state"><EmptyState icon={WifiSlash} tone="error" title="Не удалось открыть пространство" description={sessionError} action={<Btn variant="primary" onClick={()=>void checkSession()}>Попробовать снова</Btn>}/></main>;
 if(!user)return <Login error={error} onLogin={async(login,password)=>{const s=await call('login',{login,password});setCSRF(s.csrf);setUser(s.user);navigate(s.user.role==='employee'?'trajectory':'team');setError('');}}/>;
 const p=data?.profile;const employee=user.role==='employee';const catalogQuery=search.trim().toLowerCase();const candidates=data?.candidates||[];const filteredCandidates=candidates.filter(c=>(catalogAll||!c.blocked)&&[c.event.title,...c.facts].join(' ').toLowerCase().includes(catalogQuery));const activeRequests=data?.requests.filter(q=>['pending_manager','approved','pending_hr'].includes(q.status))||[];
 const names:Record<View,string>={trajectory:'Главная',catalog:'Каталог',requests:employee?'Мои шаги':'Заявки и решения',history:'История развития',team:user.role==='hr'?'Развитие команды':'Моя команда',access:'Доступ и данные',about:'Как это работает'};
 const navigation:{id:View;label:string;icon:typeof Path;count?:number}[]=[...(user.role!=='hr'?[{id:'trajectory' as View,label:'Главная',icon:House},{id:'catalog' as View,label:'Каталог',icon:SquaresFour}]:[]),...(user.role!=='employee'?[{id:'team' as View,label:'Команда',icon:UsersThree}]:[]),{id:'requests',label:employee?'Мои шаги':'Заявки и решения',icon:Flag,count:activeRequests.length},{id:'history',label:'История',icon:ClockCounterClockwise},...(user.role==='hr'?[{id:'access' as View,label:'Доступ и данные',icon:ShieldCheck}]:[])];
 return <div className={`app-shell${sidebarCollapsed?' sidebar-collapsed':''}`}><a className="skip" href="#main">Перейти к содержимому</a><aside className="sidebar" aria-label="Боковая панель"><div className="sidebar-header"><a href="#trajectory" className="brand" onClick={e=>{e.preventDefault();navigate(employee?'trajectory':'team');}}><span className="brand-logo"><img src="/halyk.svg" alt="Halyk" width={113} height={40}/></span><span className="brand-caption">Career Quest</span></a><Btn variant="ghost" shape="square" type="button" className="sidebar-toggle" onClick={toggleSidebar} aria-expanded={!sidebarCollapsed} aria-controls="sidebar-navigation" aria-label={sidebarCollapsed?'Развернуть боковую панель':'Свернуть боковую панель'} title={sidebarCollapsed?'Развернуть панель':'Свернуть панель'}><SidebarSimple size={22}/></Btn></div><nav id="sidebar-navigation" aria-label="Основная навигация">{navigation.map(({id,label,icon:Icon,count})=><a href={`#${id}`} onClick={e=>{e.preventDefault();navigate(id);}} aria-label={count?`${label}: ${count}`:label} title={sidebarCollapsed?label:undefined} aria-current={view===id?'page':undefined} key={id}><Icon size={21} weight={view===id?'fill':'regular'}/><span className="nav-label">{label}</span>{!!count&&<span className="nav-count">{count}</span>}</a>)}</nav><div className="side-bottom"><a href="#about" onClick={e=>{e.preventDefault();navigate('about');}} className="help-link" aria-label="Как это работает" title={sidebarCollapsed?'Как это работает':undefined}><Info size={20}/><span>Как это работает</span></a><div className="identity"><div className="identity-blob"><Avatar key={characterIdentity(user)} identity={characterIdentity(user)} size={46} label={`Персонаж ${p?.full_name||user.login}`}/></div><div className="identity-details"><b>{p?.full_name||user.login}</b><span>{roleName[user.role]}</span></div><Btn variant="ghost" aria-label={signingOut?'Выходим…':'Выйти'} loading={signingOut} disabled={signingOut} onClick={async()=>{setSigningOut(true);try{await call('logout',{});workspaceRequest.current++;setUser(null);setData(null);setNotice('');setCSRF('');setWorkspaceError('');setRefreshing(false);}catch(e){setError((e as Error).message);}finally{setSigningOut(false);}}}><SignOut size={21}/></Btn></div></div></aside>
 <div className="workspace"><header className="topbar"><span className="topbar-character"><Avatar key={characterIdentity(user)} identity={characterIdentity(user)} size={36} animated={false} label={`Персонаж ${p?.full_name||user.login}`}/>Развитие <CaretRight size={14}/><b>{names[view]}</b></span><div><AppBadge className="demo-label" icon={CalendarBlank} tone="blue">Демо · 1 октября 2026</AppBadge><span className="refresh-indicator" role="status">{refreshing&&data?'Обновляем…':''}</span><Btn variant="ghost" aria-label={refreshing?'Обновляем данные':'Обновить данные'} disabled={refreshing} onClick={()=>void refresh()}><ArrowsClockwise className={refreshing?'loading-spinner':undefined} size={19}/></Btn></div></header><main id="main" tabIndex={-1}>
 {notice&&<div className="notice" role="status"><CheckCircle size={20}/><span>{notice}</span><Btn variant="ghost" shape="square" className="dismiss" aria-label="Закрыть уведомление" onClick={()=>setNotice('')}><X size={18}/></Btn></div>}{error&&<div className="error" role="alert">{error}<Btn variant="ghost" shape="square" className="dismiss" onClick={()=>setError('')} aria-label="Закрыть ошибку"><X size={18}/></Btn></div>}
 {data&&workspaceError&&<div className="refresh-error" role="alert"><WarningCircle size={21}/><div><b>Не удалось обновить данные</b><p>{workspaceError} Пока показана последняя загруженная версия.</p></div><Btn onClick={()=>void refresh()}>Повторить</Btn></div>}
 {!data?(workspaceError&&!refreshing?<EmptyState icon={WifiSlash} tone="error" title="Не удалось загрузить данные" description={workspaceError} action={<Btn variant="primary" onClick={()=>void refresh()}><ArrowsClockwise size={16}/>Повторить загрузку</Btn>}/>:<WorkspaceLoading view={view}/>):<>
 {view!=='trajectory'&&<div className="page-heading"><div><h1>{names[view]}</h1>{view==='requests'&&<p>{employee?'Ваши активности и результаты.':'Заявки, которые ждут вашего решения.'}</p>}</div>{view==='requests'&&user.role!=='hr'&&<Btn onClick={()=>navigate('catalog')}><Plus size={16}/>Добавить шаг</Btn>}</div>}
 {view==='trajectory'&&p&&<Home data={data} goalControl={<GoalForm data={data} submit={g=>act('goal',{goal:g,confirmed:true},'Цель обновлена.')}/>} onCatalog={()=>navigate('catalog')} onRequests={()=>navigate('requests')} onHistory={()=>navigate('history')} onChoose={choose} onAI={askAI} aiBusy={aiBusy}/>}
 {view==='trajectory'&&!p&&<EmptyState icon={UserCircle} title="Профиль пока не заполнен" description="Попросите HR добавить данные профиля. После этого здесь появятся цель, навыки и подходящие активности." action={<Btn onClick={()=>navigate('about')}>Как это работает</Btn>}/>}
 {view==='catalog'&&<><div className="toolbar"><InputGroup className="search" size="lg"><InputGroup.Addon><MagnifyingGlass size={20}/></InputGroup.Addon><InputGroup.Input aria-label="Поиск активности" placeholder="Название или навык" value={search} onChange={e=>setSearch(e.target.value)}/></InputGroup><Checkbox label="Показать неподходящие" checked={catalogAll} onCheckedChange={setCatalogAll}/></div>
 <div className="filter-summary"><span role="status">{catalogQuery?'Найдено':'Доступно'}: {filteredCandidates.length}</span>{(search||catalogAll)&&<Btn variant="ghost" onClick={()=>{setSearch('');setCatalogAll(false);}}><X size={14}/>Сбросить фильтры</Btn>}</div>
 {filteredCandidates.length?<div className="catalog-grid">{filteredCandidates.map(c=><CandidateCard key={c.event.event_id} c={c} onChoose={()=>choose(c)} onDecline={()=>choose(c,true)}/>)}</div>:<EmptyState icon={catalogQuery?MagnifyingGlass:BookOpen} title={catalogQuery?'Активности не найдены':candidates.length?'Пока нет подходящих активностей':'Каталог пока пуст'} description={catalogQuery?'Попробуйте другое название или навык. Можно очистить поиск и посмотреть доступные активности.':candidates.length?'Сейчас активности не подходят по условиям участия. Посмотрите весь каталог — в карточках указаны причины.':'Когда HR добавит активности, здесь можно будет выбрать следующий шаг развития.'} action={catalogQuery?<Btn onClick={()=>setSearch('')}>Очистить поиск</Btn>:candidates.length?<Btn onClick={()=>setCatalogAll(true)}>Показать весь каталог<ArrowRight size={16}/></Btn>:<Btn variant="ghost" onClick={()=>navigate('trajectory')}>На главную</Btn>}/>}</>}
 {view==='requests'&&<RequestsPanel data={data} onAction={changeRequest} onCatalog={()=>navigate('catalog')}/>}
 {view==='team'&&user.role!=='employee'&&<TeamPanel data={data} dept={dept} setDept={setDept} search={search} setSearch={setSearch} onQueue={()=>navigate('requests')} onAccess={()=>navigate('access')}/>}
 {view==='history'&&<HistoryPanel data={data} onCatalog={()=>navigate('catalog')} onRequests={()=>navigate('requests')}/>}
 {view==='access'&&user.role==='hr'&&<Access data={data} call={call} done={async message=>{setNotice(message);void refresh();}}/>}
 {view==='about'&&<About/>}
 </>}
 <footer><span>Career Quest · демо</span></footer></main></div>{modal&&<Confirm config={modal} onClose={()=>setModal(null)}/>}</div>;
}

function Login({onLogin,error}:{onLogin:(login:string,password:string)=>Promise<void>;error:string}){const[login,setLogin]=useState('employee');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState(error);return <main className="login-page"><AuthStory/><section className="login-form"><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{await onLogin(login,password);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><div className="login-heading"><h2>Вход</h2></div><Input size="lg" label="Логин" name="username" disabled={busy} autoComplete="username" value={login} onChange={e=>setLogin(e.target.value)} required/><Input size="lg" label="Пароль" type="password" name="password" disabled={busy} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/>{message&&<div className="error" role="alert">{message}</div>}<Btn variant="primary" type="submit" loading={busy} aria-label={busy?'Входим…':undefined} disabled={busy}>{busy?'Входим…':'Войти'}<ArrowRight size={19}/></Btn><div className="demo-access"><b>Демо-доступ</b><Tabs variant="underline" className="role-switch" listClassName="h-11 gap-2 pb-0" value={login} onValueChange={value=>{if(!busy)setLogin(value);}} tabs={[['employee','Сотрудник'],['manager','Руководитель'],['hr','HR']].map(([value,label])=>({value,label,className:'flex-1 justify-center px-2 py-2 text-sm aria-selected:text-[var(--brand-dark)]'}))}/></div></form></section></main>;}


function GoalForm({data,submit}:{data:Workspace;submit:(g:{target_role:string;target_grade:string})=>Promise<void>}){const[open,setOpen]=useState(false);const[role,setRole]=useState(data.target?.role||'');const[grade,setGrade]=useState(data.target?.grade||'');return <><Btn onClick={()=>setOpen(true)}><Flag size={18}/>{data.target?'Изменить цель':'Выбрать цель'}</Btn>{open&&<Confirm onClose={()=>setOpen(false)} config={{title:'Цель развития',content:<><Choice label="Целевая роль" value={role} onValueChange={setRole} options={[...new Set(data.roles.map(r=>r.role))].map(r=>({value:r,label:r}))}/><Choice label="Целевой грейд" value={grade} onValueChange={setGrade} options={['Junior','Middle','Senior','Lead'].map(g=>({value:g,label:g}))}/></>,submitLabel:'Сохранить цель',onConfirm:()=>submit({target_role:role,target_grade:grade})}}/>}</>;}

function Access({data,call,done}:{data:Workspace;call:(p:string,b?:unknown)=>Promise<unknown>;done:(m:string)=>Promise<void>}){
 const[err,setErr]=useState('');const[busy,setBusy]=useState<'account'|'import'|null>(null);
 const[employee,setEmployee]=useState(data.roster.find(r=>!r.has_account)?.employee_id||'');const[role,setRole]=useState('employee');const[login,setLogin]=useState('');const[password,setPassword]=useState('');const[confirmed,setConfirmed]=useState(false);
 const[files,setFiles]=useState<{employees?:File;history?:File}>({});const[importConfirmed,setImportConfirmed]=useState(false);const formRef=useRef<HTMLFormElement>(null);
 const available=data.roster.filter(r=>!r.has_account);
 useEffect(()=>{if(!data.roster.some(r=>r.employee_id===employee&&!r.has_account))setEmployee(data.roster.find(r=>!r.has_account)?.employee_id||'');},[data.roster,employee]);
 return <div className="access-grid"><section className="access-panel"><h2>Выдать доступ</h2>
 {available.length?<form aria-busy={busy==='account'} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy('account');setErr('');try{await call('accounts',{employee_id:employee,role,login,password,confirmed});setPassword('');setLogin('');setConfirmed(false);await done('Доступ выдан.');}catch(e){setErr((e as Error).message);}finally{setBusy(null);}}}>
 <Choice label="Профиль" required disabled={!!busy} value={employee} onValueChange={setEmployee} options={available.map(r=>({value:r.employee_id,label:`${r.employee_id} · ${r.full_name} · ${r.grade}`}))}/>
 <Choice label="Роль доступа" disabled={!!busy} value={role} onValueChange={setRole} options={[{value:'employee',label:'Сотрудник'},{value:'manager',label:'Руководитель (Lead)'}]}/>
 <Input size="lg" label="Новый логин" disabled={!!busy} value={login} onChange={e=>setLogin(e.target.value)} minLength={3} maxLength={80} required autoComplete="off"/>
 <Input size="lg" label="Пароль, минимум 12 символов" disabled={!!busy} type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} maxLength={128} required autoComplete="new-password"/>
 <Checkbox label="Подтверждаю профиль и права доступа" disabled={!!busy} required checked={confirmed} onCheckedChange={setConfirmed}/>
 <Btn variant="primary" type="submit" loading={busy==='account'} aria-label={busy==='account'?'Выдаём доступ…':undefined} disabled={!!busy||!employee||!confirmed}><Plus size={18}/>{busy==='account'?'Выдаём доступ…':'Выдать доступ'}</Btn>
 {busy==='account'&&<LoadingStatus label="Создаём учётную запись…"/>}</form>:<EmptyState compact icon={data.roster.length?CheckCircle:UsersThree} tone={data.roster.length?'success':'neutral'} title={data.roster.length?'У всех сотрудников есть доступ':'Сначала добавьте сотрудников'} description={data.roster.length?'Для новых сотрудников сначала импортируйте профили. Затем здесь можно будет выдать им доступ.':'Загрузите JSON с профилями в разделе импорта. После загрузки выберите сотрудника и создайте учётную запись.'} action={<Btn onClick={()=>formRef.current?.querySelector<HTMLInputElement>('input[type="file"]')?.focus()}>Перейти к импорту<ArrowRight size={16}/></Btn>}/>}
 </section><section className="access-panel"><h2>Импорт данных</h2><p>Добавятся только новые записи.</p><div className="dataset-counts">{data.counts.employees} профилей · {data.counts.events} событий · {data.counts.skills} навыков<br/>{data.counts.history} записей истории</div>
 <form ref={formRef} aria-busy={busy==='import'} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy('import');setErr('');try{const employees=files.employees?JSON.parse(await files.employees.text()):null;const history=files.history?await files.history.text():'';await call('import',{employees,history_csv:history,confirmed:importConfirmed});setFiles({});setImportConfirmed(false);formRef.current?.reset();await done('Данные загружены.');}catch(e){setErr(e instanceof SyntaxError?'Не удалось прочитать JSON. Проверьте формат файла профилей.':(e as Error).message);}finally{setBusy(null);}}}>
 <Input size="lg" label="Профили (JSON)" type="file" disabled={!!busy} accept=".json,application/json" onChange={e=>setFiles({...files,employees:e.target.files?.[0]})}/>
 <Input size="lg" label="История участия (CSV)" type="file" disabled={!!busy} accept=".csv,text/csv" onChange={e=>setFiles({...files,history:e.target.files?.[0]})}/>
 <Checkbox label="Данные вымышленные" disabled={!!busy} checked={importConfirmed} onCheckedChange={setImportConfirmed} required/>
 <p className="muted">{!files.employees&&!files.history?'Выберите хотя бы один файл, затем подтвердите, что данные вымышленные.':!importConfirmed?'Подтвердите, что данные вымышленные, чтобы начать загрузку.':'Файлы выбраны. Можно начать загрузку.'}</p>
 <Btn variant="primary" type="submit" loading={busy==='import'} aria-label={busy==='import'?'Проверяем и загружаем…':undefined} disabled={!!busy||(!files.employees&&!files.history)||!importConfirmed}><UploadSimple size={18}/>{busy==='import'?'Проверяем и загружаем…':'Загрузить'}</Btn>
 {busy==='import'&&<LoadingStatus label="Проверяем файлы и добавляем записи…"/>}</form><p className="muted">До 500 профилей, 10 000 записей, 4 МБ.</p></section>{err&&<div className="error" role="alert">{err}</div>}</div>;
}

function About(){return <div className="about-content"><section><h2>Участие</h2><Steps status="completed"/><p>Вы выбираете активность, руководитель согласует её. После выполнения отправьте результат HR. Навыки обновятся после подтверждения.</p></section><section><h2>Рекомендации</h2><p>Подбор учитывает цель, навыки, историю и нагрузку. Совет Gemini можно запросить отдельно.</p><p>Рост навыков не меняет грейд автоматически.</p></section><section><h2>О демо</h2><p>Вымышленные профили на 1 октября 2026. Данные хранятся локально, подключения к системам банка нет.</p><details><summary>Источники и авторы</summary><p><a href="https://halykbank.kz/for-employees" target="_blank" rel="noreferrer">Halyk для сотрудников</a> · <a href="https://halykbank.kz/en/about/career/page/career" target="_blank" rel="noreferrer">Карьера в Halyk</a></p><p>Аватар: <a href="https://github.com/jeremy-prt/bloub" target="_blank" rel="noreferrer">bloub · MIT · Jérémy Perret</a>. Интерфейс: <a href="https://kumo-ui.com" target="_blank" rel="noreferrer">Kumo UI</a>, Phosphor, Manrope.</p></details></section></div>;}
