import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = name => readFileSync(resolve(root, 'backend/migrations', name), 'utf8').replace(/\r\n/g, '\n');
const target = resolve(root, 'supabase');
mkdirSync(target, { recursive: true });
const schema = ['001_supabase.sql', '002_agent.sql', '003_courses.sql']
  .map(name => `-- Source: backend/migrations/${name}\n${read(name)}`).join('\n');
const banner = '-- Generated by npm run db:sql. Edit backend/migrations sources, then regenerate.\n';
// Keep the upgrade, including its preflight and verification, in one transaction.
const withoutTransaction = sql => sql.replace(/^(?:BEGIN|COMMIT);\s*$/gm, '');
writeFileSync(resolve(target, 'schema.sql'), banner +
  '-- Schema only: does not initialize accounts/data or mark the app ready.\n' + schema);
writeFileSync(resolve(target, 'upgrade.sql'), banner + `-- Existing initialized databases only. Preserves accounts and business records.
-- Stop app writes and back up the database before upgrading. Safe to rerun.
BEGIN;
DO $preflight$
BEGIN
 IF to_regclass('career_quest.store_meta') IS NULL THEN
  RAISE EXCEPTION 'Fresh database: use data/supabase-migration.sql, not upgrade.sql';
 END IF;
 IF NOT EXISTS (SELECT 1 FROM career_quest.store_meta WHERE id = 1 AND schema_version = 1 AND ready) THEN
  RAISE EXCEPTION 'Database is not initialized or has an unsupported schema version';
 END IF;
 IF NOT EXISTS (SELECT 1 FROM career_quest.app_users) THEN
  RAISE EXCEPTION 'No application accounts: import a complete data export first';
 END IF;
END
$preflight$;
` + withoutTransaction(schema) + '\n' + withoutTransaction(read('004_course_examples.sql')) + '\n' + read('verify.sql') + '\nCOMMIT;\n');
writeFileSync(resolve(target, 'verify.sql'), banner + read('verify.sql'));
console.log('Wrote supabase/schema.sql, supabase/upgrade.sql, and supabase/verify.sql');
