import {spawnSync} from 'node:child_process';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
const go=existsSync('.tools/go/bin/go.exe')?resolve('.tools/go/bin/go.exe'):'go';
const character=spawnSync(process.execPath,['scripts/character.test.mjs'],{stdio:'inherit'});
if(character.status!==0)process.exit(character.status??1);
const api=spawnSync(process.execPath,['scripts/api.test.mjs'],{stdio:'inherit'});
if(api.status!==0)process.exit(api.status??1);
const result=spawnSync(go,['test','-v','./...'],{cwd:resolve('backend'),stdio:'inherit',env:{...process.env,GOCACHE:resolve('.tools/go-cache'),GOMODCACHE:process.env.GOMODCACHE||resolve('.tools/go-mod')}});
process.exitCode=result.status??1;
