import React, { useEffect, useRef, useContext } from 'react';
import { X, ArrowUpRight, Clock3, Monitor, MapPin, BookOpen, Sparkles, ArrowRight, Check, Target, Coins, ShieldCheck, LockKeyhole, Compass } from 'lucide-react';
import { avatar, cx, format } from './lib';
export const ErrorContext = React.createContext('');
export function Modal({title,onClose,children,wide=false}) {
  const error = useContext(ErrorContext);
  const ref=useRef(null);
  useEffect(()=>{const before=document.activeElement;ref.current.showModal();return()=>{ref.current?.close();before?.focus();};},[]);
  return <dialog ref={ref} className={cx('modal',wide&&'wide')} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-inner"><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{error&&<div className="error-banner" role="alert">{error}</div>}{children}</div></dialog>;
}
export function Pill({children,tone='green',className=''}) {return <span className={`pill ${tone} ${className}`}>{children}</span>;}
export function Progress({value,label,muted=false}) {return <div className={cx('progress',muted&&'muted')} role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value}><span style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>;}
export function Empty({title,description,action}) {return <div className="empty"><Compass size={30}/><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function Avatar({seed,frame='default',className=''}) {return <div className={`avatar ${frame} ${className}`}><img src={avatar(seed)} alt="Your customized pixel character"/></div>;}
export function QuestCard({event,onOpen,onAction,t,gameEnabled=true,featured=false,index=0}) {
  const Icon=event.type==='mentoring'?Compass:event.format==='offline'?MapPin:BookOpen;
  return <article className={cx('quest-card',featured&&'featured')} style={{'--card-index':index}}>
    <div className="quest-card-top"><span className="quest-type-icon"><Icon size={21}/></span><Pill tone={event.active?'amber':event.preparatory?'purple':event.criticalGain?'green':'neutral'}>{event.active?'IN PROGRESS':event.preparatory?'PREPARATION':event.criticalGain?'CRITICAL SKILL':event.type.toUpperCase()}</Pill><span className="quest-number">{event.event_id.replace('EV_','#')}</span></div>
    <button className="quest-title" onClick={()=>onOpen(event)}>{event.title}<ArrowUpRight size={18}/></button>
    <p className="quest-description">{event.description}</p>
    <div className="quest-meta"><span><Clock3 size={14}/>{event.duration_hours} hours</span><span>{event.format==='offline'?<MapPin size={14}/>:<Monitor size={14}/>} {event.format.replace('_',' ')}</span></div>
    <div className="skill-chips">{event.gains.slice(0,2).map(g=><span key={g.id}>{g.name}<b>+{g.after-g.before}</b></span>)}</div>
    <div className="quest-bottom">{gameEnabled?<span className="xp-label"><Sparkles size={14}/>+{event.reward.xp} XP <span className="coin-mini">· {event.reward.coins} <Coins size={12}/></span></span>:<span className="xp-label">{event.usefulGain} skill levels</span>}<button className={cx('button','small',featured&&'primary')} onClick={()=>event.active?onOpen(event):onAction(event)}>{event.active?t.resume:t.start}<ArrowRight size={15}/></button></div>
  </article>;
}
export function CharacterCard({view,t,onCustomize}) {
  return <section className="character-card panel"><div className="eyebrow">YOUR PLAYER CARD <span className="tiny-square"/></div><div className="character-stage"><span className="stage-coordinate top">PLAYER / {view.employee.employee_id}</span><Avatar seed={view.state.profile.seed} frame={view.state.profile.frame}/><span className="stage-coordinate bottom">{view.state.profile.characterClass.toUpperCase()}</span><span className="stage-plus p1">+</span><span className="stage-plus p2">+</span></div><div className="character-info"><Pill tone="purple">{view.state.profile.title}</Pill><h2>{view.state.profile.nickname||view.employee.full_name.split(' ')[0]}</h2><p>{view.employee.role}</p></div>{view.state.profile.gameEnabled&&<div className="character-xp"><div><span><Sparkles size={14}/> {t.level} {view.stats.level}</span><small>{format(view.stats.levelXp)} / 500 XP</small></div><Progress value={view.stats.levelXp/5} label="Experience to next level"/></div>}<button className="button full" onClick={onCustomize}>{t.customize}<ArrowUpRight size={15}/></button></section>;
}
export function QuestDetail({event,view,t,busy,onClose,onAct}) {
  return <Modal title={event.title} onClose={onClose} wide><div className="detail-meta"><Pill>{event.type}</Pill><span><Clock3 size={15}/> {event.duration_hours} hours</span><span>{event.format.replace('_',' ')}</span><span>{event.nextSession||'Start any time'}</span></div><p>{event.description}</p>{!event.eligible&&<div className="alert">{event.reasons.map(r=><p key={r}>{r}</p>)}</div>}<h3>{t.impact}</h3><div className="impact-grid">{event.gains.map(g=><div className="impact" key={g.id}><span>{g.name}</span><strong>{g.before}<ArrowRight size={16}/><em>{g.after}</em><small>/ 5</small></strong>{g.critical&&<small>Critical for your target</small>}</div>)}</div><div className="impact-readiness"><Target size={18}/>{t.readiness}<b>{view.readiness}% → {event.readinessAfter}%</b></div><h3>{t.why}</h3>{event.aiRationale&&<div className="ai-rationale"><Sparkles size={16}/><p>{event.aiRationale}</p></div>}<div className="evidence-list">{event.evidence.map((item,i)=><div key={item.label}><span>{String(i+1).padStart(2,'0')}</span><div><h4>{item.label}</h4><p>{item.detail}</p></div></div>)}</div><p className="muted-text small-text"><ShieldCheck size={14}/> Progress records learning, not an automatic promotion.</p><div className="modal-actions">{event.active?<><button className="button ghost" disabled={busy} onClick={()=>onAct('decline',event)}>Leave quest</button><button className="button primary" disabled={busy} onClick={()=>onAct('confirm',event)}><Check size={16}/>{t.complete}</button></>:<><button className="button ghost" disabled={busy||event.mandatory} onClick={()=>onAct('dismiss',event)}>Not for me</button><button className="button primary" disabled={busy||!event.eligible} onClick={()=>onAct('enroll',event)}>{event.eligible?<ArrowRight size={16}/>:<LockKeyhole size={16}/>} {t.start}</button></>}</div></Modal>;
}
