import { createAvatar } from '@dicebear/core';
import * as pixelArt from '@dicebear/pixel-art';
export function avatar(seed) { return createAvatar(pixelArt, { seed, backgroundColor: ['transparent'], size: 160 }).toDataUri(); }
export const format = value => Number(value).toLocaleString('en-US');
export const dateLabel = value => new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
export const cx = (...classes) => classes.filter(Boolean).join(' ');
export const translations = {
  en: {overview:'Overview',quests:'Quest board',skills:'Skill tree',character:'My character',rewards:'Rewards',journal:'Activity journal',hr:'HR observatory',settings:'Preferences',journey:'YOUR JOURNEY',workspace:'WORKSPACE',welcome:'Welcome back',adventure:'Your next chapter starts here.',sub:'A little curiosity. A meaningful next step. A career that feels like yours.',next:'Recommended for you',viewAll:'All quests',start:'Accept quest',resume:'Continue quest',details:'Quest details',complete:'Log completion',coins:'Qadam coins',level:'Level',completed:'Quests completed',readiness:'Target readiness',nextGrade:'YOUR CAREER PATH',customize:'Customize character',guide:'Career guide',ask:'Ask your guide',active:'Active quests',empty:'No active quests yet. Choose a step that feels right for you.',target:'Career target',edit:'Change target',recommended:'Recommended',all:'All activities',available:'Available',required:'Required training',search:'Search quests or skills',close:'Close',save:'Save changes',cancel:'Cancel',why:'Why this quest?',impact:'Your skill impact',evidence:'Based on your profile, target, and history',future:'GROW AT YOUR OWN PACE',voluntary:'Your journey is voluntary. No leaderboards. No pressure.',signout:'Sign out',demo:'Local demo',inspect:'Explore a profile',loading:'Loading your journey…'},
  ru: {overview:'Обзор',quests:'Доска квестов',skills:'Дерево навыков',character:'Мой персонаж',rewards:'Награды',journal:'История активностей',hr:'HR-обзор',settings:'Настройки',journey:'ВАШ ПУТЬ',workspace:'ПРОСТРАНСТВО',welcome:'С возвращением',adventure:'Следующая глава начинается здесь.',sub:'Любопытство, осмысленный шаг и карьера, которую выбираете вы.',next:'Рекомендуем вам',viewAll:'Все квесты',start:'Принять квест',resume:'Продолжить квест',details:'Подробнее о квесте',complete:'Подтвердить завершение',coins:'Монеты Qadam',level:'Уровень',completed:'Завершено квестов',readiness:'Готовность к цели',nextGrade:'ВАШ КАРЬЕРНЫЙ ПУТЬ',customize:'Настроить персонажа',guide:'Карьерный навигатор',ask:'Спросить навигатора',active:'Активные квесты',empty:'Пока нет активных квестов. Выберите подходящий шаг.',target:'Карьерная цель',edit:'Изменить цель',recommended:'Рекомендуемые',all:'Все активности',available:'Доступные',required:'Обязательное обучение',search:'Поиск квестов и навыков',close:'Закрыть',save:'Сохранить',cancel:'Отмена',why:'Почему этот квест?',impact:'Изменение навыков',evidence:'На основе профиля, цели и истории',future:'РАЗВИВАЙТЕСЬ В СВОЁМ ТЕМПЕ',voluntary:'Участие добровольное. Без рейтингов и давления.',signout:'Выйти',demo:'Локальное демо',inspect:'Выбрать профиль',loading:'Загружаем ваш путь…'},
  kk: {overview:'Шолу',quests:'Квест тақтасы',skills:'Дағдылар ағашы',character:'Менің кейіпкерім',rewards:'Марапаттар',journal:'Белсенділік тарихы',hr:'HR шолуы',settings:'Баптаулар',journey:'СІЗДІҢ ЖОЛЫҢЫЗ',workspace:'КЕҢІСТІК',welcome:'Қайта қош келдіңіз',adventure:'Келесі тарау осы жерден басталады.',sub:'Қызығушылық, маңызды қадам және өзіңіз таңдаған мансап.',next:'Сізге ұсынылады',viewAll:'Барлық квесттер',start:'Квестті қабылдау',resume:'Квестті жалғастыру',details:'Квест туралы',complete:'Аяқталғанын растау',coins:'Qadam монеталары',level:'Деңгей',completed:'Аяқталған квесттер',readiness:'Мақсатқа дайындық',nextGrade:'МАНСАП ЖОЛЫҢЫЗ',customize:'Кейіпкерді баптау',guide:'Мансап бағыттаушысы',ask:'Бағыттаушыдан сұрау',active:'Белсенді квесттер',empty:'Әзірге белсенді квест жоқ. Өзіңізге қолайлы қадамды таңдаңыз.',target:'Мансап мақсаты',edit:'Мақсатты өзгерту',recommended:'Ұсынылған',all:'Барлық іс-шаралар',available:'Қолжетімді',required:'Міндетті оқу',search:'Квест немесе дағды іздеу',close:'Жабу',save:'Сақтау',cancel:'Бас тарту',why:'Неліктен бұл квест?',impact:'Дағдылардың өсуі',evidence:'Профиль, мақсат және тарих негізінде',future:'ӨЗ ҚАРҚЫНЫҢЫЗБЕН ДАМЫҢЫЗ',voluntary:'Қатысу ерікті. Рейтингсіз және қысымсыз.',signout:'Шығу',demo:'Жергілікті демо',inspect:'Профиль таңдау',loading:'Жолыңыз жүктелуде…'}
};
